# Generated by Django 5.0.1 on 2024-01-06 07:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('taipei', '台北'), ('new_taipei', '新北'), ('keelung', '基隆'), ('taoyuan', '桃園'), ('hsinchu', '新竹'), ('miaoli', '苗栗'), ('taichung', '台中'), ('changhua', '彰化'), ('nantou', '南投'), ('yunlin', '雲林'), ('chiayi', '嘉義'), ('tainan', '台南'), ('kaohsiung', '高雄'), ('pingtung', '屏東'), ('yilan', '宜蘭'), ('hualien', '花蓮'), ('taitung', '台東')], max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_1', models.CharField(max_length=255)),
                ('sub_2', models.CharField(max_length=255)),
                ('sub_3', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hour', models.CharField(max_length=255)),
                ('min', models.CharField(max_length=255)),
                ('tel', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('cus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
        ),
    ]
