# Generated by Django 5.0.1 on 2024-01-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='sub_1',
            field=models.CharField(choices=[('bana', '香蕉'), ('choco', '巧克力醬'), ('strjam', '草莓果醬'), ('bluejam', '藍莓果醬'), ('taro', '芋泥'), ('corn', '玉米'), ('hon', '蜂蜜'), ('but', '奶油'), ('chee', '起司'), ('ham', '火腿'), ('egg', '蛋'), ('eg', '半熟蛋'), ('bac', '培根'), ('oni', '洋蔥'), ('toma', '番茄'), ('cab', '高麗菜'), ('tuna', '鮪魚'), ('pork', '豬肉'), ('chi', '雞肉'), ('beef', '牛肉')], max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sub_2',
            field=models.CharField(choices=[('bana', '香蕉'), ('choco', '巧克力醬'), ('strjam', '草莓果醬'), ('bluejam', '藍莓果醬'), ('taro', '芋泥'), ('corn', '玉米'), ('hon', '蜂蜜'), ('but', '奶油'), ('chee', '起司'), ('ham', '火腿'), ('egg', '蛋'), ('eg', '半熟蛋'), ('bac', '培根'), ('oni', '洋蔥'), ('toma', '番茄'), ('cab', '高麗菜'), ('tuna', '鮪魚'), ('pork', '豬肉'), ('chi', '雞肉'), ('beef', '牛肉')], max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sub_3',
            field=models.CharField(choices=[('bana', '香蕉'), ('choco', '巧克力醬'), ('strjam', '草莓果醬'), ('bluejam', '藍莓果醬'), ('taro', '芋泥'), ('corn', '玉米'), ('hon', '蜂蜜'), ('but', '奶油'), ('chee', '起司'), ('ham', '火腿'), ('egg', '蛋'), ('eg', '半熟蛋'), ('bac', '培根'), ('oni', '洋蔥'), ('toma', '番茄'), ('cab', '高麗菜'), ('tuna', '鮪魚'), ('pork', '豬肉'), ('chi', '雞肉'), ('beef', '牛肉')], max_length=255),
        ),
    ]
