# Generated by Django 5.0.1 on 2024-01-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_booking_num_booking_toast_alter_booking_sub_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tel',
            field=models.IntegerField(null=True),
        ),
    ]
