# Generated by Django 5.0.1 on 2024-01-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_booking_address_alter_booking_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cus',
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
