# Generated by Django 5.0.1 on 2024-01-09 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_booking_cus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sub_1',
            field=models.CharField(choices=[('草莓', '草莓 +15'), ('酪梨', '酪梨 +15'), ('起司', '起司 +10'), ('培根', '培根 +15'), ('雞肉', '雞肉 +15'), ('紅豆', '紅豆 +5'), ('抹茶', '抹茶 +5'), ('蛋', '蛋 +10'), ('半熟蛋', '半熟蛋 +10'), ('玉米', '玉米 +5'), ('火腿', '火腿 +15'), ('洋蔥', '洋蔥 +5'), ('番茄', '番茄 +5'), ('高麗菜', '高麗菜 +10'), ('鮪魚', '鮪魚 +5'), ('豬肉', '豬肉 +10'), ('牛肉', '牛肉 +25'), ('馬鈴薯沙拉', '馬鈴薯沙拉 +5'), ('香蕉', '香蕉 +5'), ('巧克力醬', '巧克力醬 +5'), ('草莓果醬', '草莓果醬 +5'), ('藍莓果醬', '藍莓果醬 +5'), ('棉花糖', '棉花糖 +10'), ('芋泥', '芋泥 +5'), ('蜂蜜', '蜂蜜 +5'), ('奶油', '奶油 +5')], max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sub_2',
            field=models.CharField(choices=[('草莓', '草莓 +15'), ('酪梨', '酪梨 +15'), ('起司', '起司 +10'), ('培根', '培根 +15'), ('雞肉', '雞肉 +15'), ('紅豆', '紅豆 +5'), ('抹茶', '抹茶 +5'), ('蛋', '蛋 +10'), ('半熟蛋', '半熟蛋 +10'), ('玉米', '玉米 +5'), ('火腿', '火腿 +15'), ('洋蔥', '洋蔥 +5'), ('番茄', '番茄 +5'), ('高麗菜', '高麗菜 +10'), ('鮪魚', '鮪魚 +5'), ('豬肉', '豬肉 +10'), ('牛肉', '牛肉 +25'), ('馬鈴薯沙拉', '馬鈴薯沙拉 +5'), ('香蕉', '香蕉 +5'), ('巧克力醬', '巧克力醬 +5'), ('草莓果醬', '草莓果醬 +5'), ('藍莓果醬', '藍莓果醬 +5'), ('棉花糖', '棉花糖 +10'), ('芋泥', '芋泥 +5'), ('蜂蜜', '蜂蜜 +5'), ('奶油', '奶油 +5')], max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sub_3',
            field=models.CharField(choices=[('草莓', '草莓 +15'), ('酪梨', '酪梨 +15'), ('起司', '起司 +10'), ('培根', '培根 +15'), ('雞肉', '雞肉 +15'), ('紅豆', '紅豆 +5'), ('抹茶', '抹茶 +5'), ('蛋', '蛋 +10'), ('半熟蛋', '半熟蛋 +10'), ('玉米', '玉米 +5'), ('火腿', '火腿 +15'), ('洋蔥', '洋蔥 +5'), ('番茄', '番茄 +5'), ('高麗菜', '高麗菜 +10'), ('鮪魚', '鮪魚 +5'), ('豬肉', '豬肉 +10'), ('牛肉', '牛肉 +25'), ('馬鈴薯沙拉', '馬鈴薯沙拉 +5'), ('香蕉', '香蕉 +5'), ('巧克力醬', '巧克力醬 +5'), ('草莓果醬', '草莓果醬 +5'), ('藍莓果醬', '藍莓果醬 +5'), ('棉花糖', '棉花糖 +10'), ('芋泥', '芋泥 +5'), ('蜂蜜', '蜂蜜 +5'), ('奶油', '奶油 +5')], max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='toast',
            field=models.CharField(choices=[('蜂蜜麥片吐司', '蜂蜜麥片吐司 $45'), ('白吐司', '白吐司 $20'), ('全麥吐司', '全麥吐司 $40'), ('多穀吐司', '多穀吐司 $35'), ('法式麵包', '法式麵包 $30'), ('全素吐司', '全素吐司 $20')], default='1', max_length=255),
        ),
    ]
